#include<stdio.h>
void main()
{
    FILE *f1,*f2,*f3;
    char ch;
    f1=fopen("S2.txt","w");
    ch=getchar();
    while(ch!='@')
    {
        fputc(ch,f1);
        ch=getchar();
    }
    fclose(f1);
    f2=fopen("S3.txt","w");
    ch=getchar();
    while(ch!='@')
    {
        fputc(ch,f2);
        ch=getchar();
    }
    fclose(f2);
    f3=fopen("S4.txt","w");
    f1=fopen("S2.txt","r");
    ch=fgetc(f1);
    while(ch!=EOF)
    {
        fputc(ch,f3);
        ch=fgetc(f1);
    }
    fclose(f1);
    f2=fopen("S3.txt","r");
    ch=fgetc(f2);
    while(ch!=EOF)
    {
        fputc(ch,f3);
        ch=fgetc(f2);
    }
    fclose(f2);
    fclose(f3);
    f3=fopen("S4.txt","r");
    ch=fgetc(f3);
    while(ch!=EOF)
    {
        printf("%c",ch);
        ch=fgetc(f3);
    }
    fclose(f3);
}